### ISSUE TITLE
Feature Suggestion: Right Click from Terminal

### ISSUE THREAD

**Issue by WayneLambert** [kameshkotwani/google-search#1]
Hi Kamesh,

This is a really useful simple extension for productivity. Do you think it would be possible to make the 'Google this' text available for a right click action from within the terminal as well as the editor? This could be useful for when the terminal gives you an error message and you would like to Google that message quickly.

Specifically, I am using VS Code for Mac (v1.32.3), version 1.0 of the extension and the z shell (zsh) from within the integrated terminal.

Thanks,

Wayne

**Comment by kameshkotwani** [comment]
currently, right click is not supported in integrated terminal in vscode. In future, if that happes, I'll definitely add this feature!

**Comment by bruteforks** [comment]
was coming here to suggest this haha
