### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by rafzei** [kameshkotwani/google-search#27]
I would love to see this feature also in vs code terminal.
Is it possible?

**Comment by casellimarco** [comment]
@kameshkotwani this would be quite useful, Do you have any plans to add it?

**Comment by kameshkotwani** [comment]
> @kameshkotwani this would be quite useful, Do you have any plans to add it?

Unfortunately, the click context menu is not currently supported in Terminal, so right now, it's not possible.
